name: Deploy Cloud Resume

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ---------- CHECKOUT ----------
    - name: Checkout repo
      uses: actions/checkout@v4

    # ---------- AZURE LOGIN (OIDC) ----------
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # ---------- TERRAFORM ----------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: terraform
      run: |
        terraform apply -auto-approve \
          -var="storage_account_name=tfcloudresume" \

    # ---------- SITE UPLOAD ----------
    - name: Upload site to Azure Storage
      run: |
        az storage blob upload-batch \
          --account-name tfcloudresume1 \
          --destination '$web' \
          --source site \
          --overwrite

    # ---------- FRONT DOOR CACHE PURGE ----------
    - name: Purge Azure Front Door cache
      run: |
        az afd endpoint purge \
          --resource-group tp-cloud-resume1 \
          --endpoint-name cloud-resume-endpoint \
          --content-paths "/*"
